/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Game.BadConsequence;

/**
 *
 * @author fdavidcl
 */
public class BadConsequenceView extends javax.swing.JPanel {
    private BadConsequence badModel;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }
    
    public void setBad(BadConsequence b) {
        badModel = b;
        
        badContent.setText(badModel.getText());
        
        if (badModel.kills()) {
            deathLabel.setVisible(true);
            levelsLabel.setVisible(false);
            hiddenLabel.setVisible(false);
            visibleLabel.setVisible(false);
        } else {
            deathLabel.setVisible(false);
            levelsLabel.setText("-" + Integer.toString(badModel.getLevels()) + " niveles");
            
            if (badModel.getSpecificVisibleTreasures().isEmpty() && badModel.getSpecificHiddenTreasures().isEmpty()) {
                hiddenLabel.setText(Integer.toString(badModel.getHiddenTreasures()) + " ocultos");
                visibleLabel.setText(Integer.toString(badModel.getVisibleTreasures()) + " visibles");
            } else {
                hiddenLabel.setText("Ocultos: " + badModel.getSpecificHiddenTreasures());
                visibleLabel.setText("Visibles: " + badModel.getSpecificVisibleTreasures());
            }
        }
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        badText = new javax.swing.JLabel();
        visibleLabel = new javax.swing.JLabel();
        hiddenLabel = new javax.swing.JLabel();
        levelsLabel = new javax.swing.JLabel();
        deathLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        badContent = new javax.swing.JTextArea();

        badText.setFont(badText.getFont());
        badText.setText("Mal rollo:");

        visibleLabel.setFont(visibleLabel.getFont().deriveFont(visibleLabel.getFont().getSize()-2f));
        visibleLabel.setText("Visible lost");

        hiddenLabel.setFont(hiddenLabel.getFont().deriveFont(hiddenLabel.getFont().getSize()-2f));
        hiddenLabel.setText("Hidden lost");

        levelsLabel.setFont(levelsLabel.getFont().deriveFont(levelsLabel.getFont().getSize()-2f));
        levelsLabel.setText("Levels lost");

        deathLabel.setFont(deathLabel.getFont());
        deathLabel.setText("Muerte");

        badContent.setColumns(20);
        badContent.setLineWrap(true);
        badContent.setRows(2);
        badContent.setTabSize(1);
        badContent.setText("Pierdes...");
        badContent.setFocusable(false);
        jScrollPane1.setViewportView(badContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(badText)
                            .addComponent(levelsLabel)
                            .addComponent(deathLabel)
                            .addComponent(visibleLabel)
                            .addComponent(hiddenLabel))
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(badText)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visibleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hiddenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deathLabel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea badContent;
    private javax.swing.JLabel badText;
    private javax.swing.JLabel deathLabel;
    private javax.swing.JLabel hiddenLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel levelsLabel;
    private javax.swing.JLabel visibleLabel;
    // End of variables declaration//GEN-END:variables
}
